### ISSUE TITLE
[BUG] Mount up works for some tokens and not others

### ISSUE THREAD

**Issue by amcvfx** [p4535992/MountUp#12]
Foundry 9.269
FoundryVTT Mount Up! 3.2.19
Token Attacher 4.4.5
Token Z 0.6.5

I am having issues where only some tokens will work with Mount Up and I can't figure out what the cause is. With only the above modules active, pressing the mount up button will do nothing (and no error message). It happens regardless of if the token is a character or NPC. It works with some and doesn't work with others.
Sorry, not much help here but I can't find any consistency.

**Comment by p4535992** [comment]
maybe some flag is stuck..., select these tokens and try to run this macro:
`game.modules.get('foundryvtt-mountup').api.cleanUpTokenSelected()`
let me know if the issue persist.

**Comment by Threvlin** [comment]
Hey there, just made an account so that I could say this fixed my problem. I had one player character that hasn't been able to mount up for weeks now, even when I made the character again from scratch and dragged stuff over I'd keep testing it to make sure it worked after everything I moved over, trying to narrow things down, it kept working, and then I'd refresh and the new token stopped working as well. Can't say at this time what caused the issue, but the macro fixed it until further notice.

Thank you!

**Comment by shecrio** [comment]
This also fixed two different problems I had, one token that automatically dismounted itself and another that couldn't be mounted to things at all. It might be a good idea to include a button somewhere in the module to do this because it worked great.

**Comment by p4535992** [comment]
Added a new HUD button . When righ click ona token with no rider or mout, IF THERE IS SOME FLAGS FROM THE MODULE MOUNT UP it will show up a button for clean up the data without the need to run the macro.

**Comment by Threvlin** [comment]
Awesome. Thankfully haven't run into it again yet but in case it does show up this should be extremely handy.
